[General]
Font="Noto Sans"
ClockEnabled="true"
ClockPosition="center"
CustomBackground="false"
LoginBackground="true"
Background="backgrounds/wallpaper.jpg"
FontSize=14
bgDark      = "#060608"
bgDefault   = "#060608"
textDefault             = "#aaaaac"
textHighlight           = "#dadadc"
textPlaceholder         = "#7f8c8d"
buttonBgNormal          = "#101012"
buttonBorderNormal      = "#222224"
buttonBgHovered0        = "#1a1a1c"
buttonBgHovered1        = "#161618"
buttonBorderHovered     = "#3a3a3c"
buttonBgPressed         = "#1e1e20"
buttonBorderPressed     = "#4a4a4c"
buttonBgFocused0        = "#1a1a1c"
buttonBgFocused1        = "#1a1a1c"
buttonBorderFocused     = "#3a3a3c"
lineeditBgNormal        = "#101012"
lineeditBorderNormal    = "#222224"
lineeditBorderHovered   = "#3a3a3c"
lineeditBorderFocused   = "#3a3a3c"
viewitemBgHovered       = "#161618"
viewitemBorderHovered   = "#2c2c2e"
viewitemBgPressed       = "#1e1e20"
viewitemBorderPressed   = "#3a3a3c"
opacityPanel    = "0.95"
opacityDefault  = "0.90"
